### ISSUE TITLE
Pin definition 32bit Board

### ISSUE THREAD

**Issue by Sundancer78** [audiobrian/tld3pro_klipper#1]
Why don't you take the pin definition for the Tenlog 32bit board from the pin definition of the Tenlog firmware?
Shouldn't all the information be there?

#define BOARD_INFO_NAME "TENLOG v3.1.1"
#define DEFAULT_MACHINE_NAME "TENLOG 3D"

#define BOARD_NO_NATIVE_USB
/* LED0 Port/Pin definition */
#define LED0 PB7 // TEST

//#define OLD_PIN

/*
  * SDIO pins
  */
#define BOARD_SDIO_D0 PC8
#define BOARD_SDIO_D1 PC9
#define BOARD_SDIO_D2 PC10
#define BOARD_SDIO_D3 PC11
#define BOARD_SDIO_CLK PC12
#define BOARD_SDIO_CMD PD2
#define BOARD_SDIO_DET PE14

and so forth......

**Comment by audiobrian** [comment]
I don't understand what is the issue here

**Comment by Sundancer78** [comment]
I gathered from the documentation or the readme that the pin assignment of the 32-bit board is not clear. But I probably misinterpreted the content.
So I thought that you could use the pin assignment from the definition file of the current firmware.

**Comment by audiobrian** [comment]
Before starting following the tracks with microscope and the multimeter I tried to identify all those pins in the Marlin code without success, because the pin definition was not clear for me. Also, I liked to discovered what pins were unused, since I decided to make available those unused pins.

Anyway, the biggest challenge with this board was to identify the clocks and registers for every pin, since Klipper does not support this 100 pins package version of the MCU, so, with all the manual task of tracking the connections and using the MCU datasheet, I could modify klipper and create the binary file and make it work.
